Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,44 +1,44 @@
 #!/bin/bash
 
-RED=$'\033[1;31m'
-GREEN=$'\033[1;32m'
-YELLOW=$'\033[1;33m'
-BLUE=$'\033[1;34m'
-PURPLE=$'\033[1;35m'
-GRAY=$'\033[1;30m'
-CYAN=$'\033[1;36m'
-WHITE=$'\033[1;37m'
-NC=$'\033[0m'
+RED='\033[1;31m'
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[1;34m'
+PURPLE='\033[1;35m'
+GRAY='\033[1;30m'
+CYAN='\033[1;36m'
+WHITE='\033[1;37m'
+NC='\033[0m'
 
 if [ -f "tmxlogin" ]; then
 
-    echo "${GREEN}Available${NC}"
+    echo -e "${GREEN}Available${NC}"
 
-    if ! "chmod +x *"; then
-        echo "${RED}Exicute Permission provide Eroor${NC}"
+    if ! chmod +x *; then
+        echo -e "${RED}Execute Permission Provide Error${NC}"
     else
-        echo "${GREEN}Exicute Permission Provide Done${NC}"
+        echo -e "${GREEN}Execute Permission Provided${NC}"
     fi
 
-    if ! cp -f tmxlogin ../usr/bin/; then
-        echo "${RED}File [ tmxlogin ] coppy Eroor${NC}"
+    if ! cp -f tmxlogin /usr/bin/; then
+        echo -e "${RED}File [ tmxlogin ] copy Error${NC}"
     else
-        echo "${GREEN}File [ tmxlogin ] coppy Done ${NC}"
+        echo -e "${GREEN}File [ tmxlogin ] copied successfully ${NC}"
     fi
 
-    if ! grep -q 'tmxlogin' ../usr/etc/bash.bashrc; then
-        if ! echo 'tmxlogin' >> ../usr/etc/bash.bashrc; then
-            echo "${RED}File can't set in .bashrc file${NC}"
+    if ! grep -q 'tmxlogin' /usr/etc/bash.bashrc; then
+        if ! echo 'tmxlogin' >> /usr/etc/bash.bashrc; then
+            echo -e "${RED}Can't set file in .bashrc file${NC}"
         else
-            echo "${GREEN}File set on .bashrc file${NC}"
+            echo -e "${GREEN}File set on .bashrc file${NC}"
         fi
 
-        echo "${GREEN}All Done ${NC}"
-        echo "${GREEN}Join Our Telegram Channel${NC}"
+        echo -e "${GREEN}All Done ${NC}"
+        echo -e "${GREEN}Join Our Telegram Channel${NC}"
         sleep 1
         xdg-open https://t.me/cyber_man_root
+    fi
 
 else
-    echo "${RED}File not found${NC}"
+    echo -e "${RED}File not found${NC}"
 fi
-
